### PR TITLE
Feat: Add wandb

### PR DESCRIPTION
**Pull request by NanoCode012**
Adds wandb for tracking runs.

Usage: pass 
- `--wandb_project "name" ` 
- `--run_name "name"` (optional)

It also detects if environment already set and passes `report_to='wandb'`

Test run passing `wandb_project` and `run_name`:
```bash
$ python finetune.py --base_model <redact> --output_dir test-report --wandb_project <redact> --run_name test-reporting --data_path '../alpaca_data_cleaned.json'
Training Alpaca-LoRA model with params:
...
wandb_project: <redact>
run_name: test-reporting
...
wandb: Tracking run with wandb version 0.14.0
wandb: Run data is saved locally in <redact>
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run test-reporting
wandb: ⭐️ View project at <redact>
wandb: 🚀 View run at <redact>
```

Test run passing only `wandb_project`:
```
$ python finetune.py --base_model <redact> --output_dir test-report --wandb_project <redact>  --data_path '../alpaca_data_cleaned.json'
Training Alpaca-LoRA model with params:
...
wandb_project: <redact>
run_name:
...
wandb: Tracking run with wandb version 0.14.0
wandb: Run data is saved locally in <redact>
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lucky-grass-17 # <- random name
```

### CODE REVIEW

**Comment by eryk-mazus** [comment]
would it be useful to add `.watch()` as well ?

**Comment by NanoCode012** [comment]
> would it be useful to add `.watch()` as well ?

Hello @eryk-mazus , I have never used that command before. However, following this https://docs.wandb.ai/guides/integrations/huggingface#additional-wb-settings , it should be as simple as setting the env `WANDB_WATCH=all`, am I correct?

While we're on this topic, perhaps it would be interesting to add `WANDB_LOG_MODEL` as an option as well?

**Comment by NanoCode012** [comment]
Hello @eryk-mazus, I have added that feature.

**Comment by eryk-mazus** [comment]
Nice, thanks

**Pull request merged**
