### PR TITLE
Templated prompter

### PR DESCRIPTION
**Pull request by AngainorDev**
Extending on https://github.com/tloen/alpaca-lora/pull/86

After experimenting with several different LoRAs that used a different prompt template, I began with hard coding variants but now feel the need for a more flexible system.

This also make the current repo directly compatible with localised models like Vigogne, and useable for more exotic prompts as well.

### CODE REVIEW

**Comment by AngainorDev** [comment]
Shall I resolve the new conflicts now, or will do address when/if merging?

**Comment by claysauruswrecks** [comment]
@AngainorDev I think there are too many notifications happening right now, you'll have to tag @tloen explicitly to get yes/no on if this is acceptable path. Probably easiest to rebase and fix conflicts, then tag when ready for merge.

I think this is a good idea.

**Comment by AngainorDev** [comment]
@tloen 
I rebased the PR.
Hoping you like the way it goes.

The linter check confuses me. 
Complained with 2 empty lines saying to remove one, complains requiring one more once removed.
No error on my local linter/black.

**Comment by tloen** [comment]
Fixed this up a bit, should be good to go. Agree it's a very good idea.

**Pull request merged**
