### PR TITLE
Default dataset to cleaned alpaca dataset from HF

### PR DESCRIPTION
**Pull request by gururise**
Simple change to default the dataset to the Hugging Face dataset repo for the Cleaned Alpaca dataset, rather than loading the local json, which will likely be out of date.

### CODE REVIEW

**Comment by tloen** [comment]
Makes sense. How often do you plan to update the Hugging Face dataset, by the way?

**Comment by eryk-mazus** [comment]
Wasn't that merged already
https://github.com/tloen/alpaca-lora/issues/167

**Comment by gururise** [comment]
> Wasn't that merged already #167

Only the README.md was updated.  The finetune.py was not.

**Comment by gururise** [comment]
> Wasn't that merged already #167

Only the README.md was updated.  The finetune.py was not.

**Comment by gururise** [comment]
> Makes sense. How often do you plan to update the Hugging Face dataset, by the way?

Will generally keep the HF dataset in sync with the github repo. Will likely not sync each individual minor commit; however, after collecting a series of commits/PR's that are reviewed, planning to make a release and push to HF.

**Comment by tloen** [comment]
My reasoning for not updating the default in the code was that I didn't want to have any external dependencies in the code itself (besides my own repo, of course). Users can get a generally better experience pointing their clients to the decapoda HF checkpoints and the cleaned huggingface dataset, which is why I add them to the README, but I do want the default settings to work every time. I'd be comfortable pointing the code directly to the upstream repo if I had a sense that it wouldn't ship any dangerous/breaking changes.

**Comment by tloen** [comment]
Ah whatever. Move fast and break things

**Pull request merged**
